# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class Finding(BaseModel):
    category: typing.Optional[types.Category] = None
    severity: typing.Optional[types.Severity] = None
    title: typing.Optional[str] = Field(default=None, description='one line')
    evidence: typing.Optional[str] = Field(default=None, description='a VERBATIM quote from the transcript that shows it; copy it, never paraphrase')
    reproduce: typing.Optional[str] = Field(default=None, description='the commands a person would type to see it again')
    confidence: typing.Optional[float] = Field(default=None, description='0.0 to 1.0')

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (1)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
Finding.model_rebuild()
