# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class Category(str, Enum):
    FILE_PERMISSIONS = "FILE_PERMISSIONS"
    SECRET_EXPOSURE = "SECRET_EXPOSURE"
    UNSAFE_DEFAULT = "UNSAFE_DEFAULT"
    INJECTION = "INJECTION"
    INSECURE_TRANSPORT = "INSECURE_TRANSPORT"
    USABILITY = "USABILITY"
    OTHER = "OTHER"

class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class StepKind(str, Enum):
    TYPE = "TYPE"
    KEY = "KEY"
    WAIT = "WAIT"
    DONE = "DONE"

# #########################################################################
# Generated classes (2)
# #########################################################################

class DrillStep(BaseModel):
    kind: StepKind
    text: typing.Optional[str] = Field(default=None, description='for TYPE: the exact characters to type')
    enter: typing.Optional[bool] = Field(default=None, description='for TYPE: press Enter after the text')
    key: typing.Optional[str] = Field(default=None, description='for KEY: one of enter, escape, up, down, ctrl-c')
    why: str = Field(description='one line: what you are trying and why')

class Finding(BaseModel):
    category: Category
    severity: Severity
    title: str = Field(description='one line')
    evidence: str = Field(description='a VERBATIM quote from the transcript that shows it; copy it, never paraphrase')
    reproduce: str = Field(description='the commands a person would type to see it again')
    confidence: float = Field(description='0.0 to 1.0')

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (2)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
DrillStep.model_rebuild()
Finding.model_rebuild()
